default_button: true
default_message: true
default_tab: true
default_tab_edit: true
_core:
  default_config_hash: ffjwyOkkEGJcHRBGwLlGLtdWUcTvXx8Dclcq43MZrT8
button:
  production_facilities_services: true
  blog: true
  musician: true
  flim: true
  new_film: true
  name: true
message:
  production_facilities_services: true
  blog: true
  musician: true
  flim: true
  new_film: true
  name: true
tab:
  production_facilities_services: true
  blog: true
  musician: true
  flim: true
  new_film: true
  name: true
tab_edit:
  production_facilities_services: true
  blog: true
  musician: true
  flim: true
  new_film: true
  name: true
