schemas:
  bootstrap: 8000
  cion: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://dev-cion2.pantheonsite.io/themes/cion/favicon.ico'
  use_default: true
cdn_jsdelivr_theme: darkly
table_responsive: '-1'
table: ''
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
