module:
  addanother: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  backup_migrate: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  blocktabs: 0
  breakpoint: 0
  chosen: 0
  chosen_field: 0
  chosen_lib: 0
  cion_crew_database: 0
  cion_migrate: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_devel: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  empty_front_page: 0
  entity: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  google_analytics_reports: 0
  google_analytics_reports_api: 0
  help: 0
  history: 0
  image: 0
  kint: 0
  layout_discovery: 0
  link: 0
  media_entity: 0
  media_entity_spotify: 0
  menu_ui: 0
  migrate: 0
  migrate_plus: 0
  migrate_tools: 0
  module_filter: 0
  node: 0
  options: 0
  page_cache: 0
  page_manager: 0
  panels: 0
  path: 0
  profile: 0
  quickedit: 0
  rdf: 0
  redirect_after_login: 0
  search_api: 0
  search_api_db: 0
  search_api_db_defaults: 0
  shortcut: 0
  simplelogin: 0
  system: 0
  tablefield: 0
  taxonomy: 0
  text: 0
  toolbar: 0
  total_control: 0
  tour: 0
  update: 0
  user: 0
  varbase_total_control: 0
  video: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  webform: 0
  webform_node: 0
  webform_ui: 0
  menu_link_content: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap: 0
  cion: 0
  cion2: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
